name: maali_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

#------------PACKAGES-------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http : ^1.2.1
  intl : ^0.19.0
  logger: ^2.0.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.1
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0






  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2
  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1



  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.10
  cached_network_image: ^3.3.1
  firebase_performance: ^0.9.4+4



  #--------------------- ./  PACKAGES END ------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  #----------------------- LOCAL ASSETS --------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/extra/
    - assets/images/on_boarding_images/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/profile_images/
    - assets/images/products/product_images/
    - assets/icons/payment_methods/

  #---------------------- LOCAL FONTS ---------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 400
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400

        - asset: assets/fonts/Poppins-Light.ttf
          weight: 500
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset:  assets/fonts/Poppins-MediumItalic.ttf
          weight: 500

        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset:  assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 400



